// GENERATED by scripts/build-patterns.mjs. Do not edit.
// Source: vendor/chromium-autofill/legacy_regex_patterns.json (BSD-3-Clause,
// see vendor/chromium-autofill/README.md). Locale "en", 23 variants
// across 12 field types and 9 vetoes.
//
// Regenerate with `pnpm patterns`. CI runs `pnpm patterns:check`, which fails
// when this file and the vendored source have drifted apart.
import type { FieldKind } from './types';

export interface PatternVariant {
  readonly positive: string;
  readonly negative: string | null;
  readonly score: number;
  /** Chromium's attribute names: LABEL, NAME, and so on. */
  readonly attributes: readonly string[];
  /** Chromium's control-type names: INPUT_TEXT, SELECT_ONE, and so on. */
  readonly controls: readonly string[];
}

export interface PatternEntry {
  readonly type: string;
  readonly kind: FieldKind;
  readonly variants: readonly PatternVariant[];
}

export interface VetoEntry {
  readonly type: string;
  /** null vetoes every kind; a list vetoes only those kinds. */
  readonly scope: readonly FieldKind[] | null;
  readonly variants: readonly PatternVariant[];
}

export const CHROMIUM_PATTERNS: {
  readonly positives: readonly PatternEntry[];
  readonly vetoes: readonly VetoEntry[];
} = {
  "positives": [
    {
      "type": "FIRST_NAME",
      "kind": "given_name",
      "variants": [
        {
          "positive": "first.*name|initials|fname|first$|given.*name",
          "negative": null,
          "score": 0.9,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT"
          ]
        }
      ]
    },
    {
      "type": "LAST_NAME",
      "kind": "family_name",
      "variants": [
        {
          "positive": "last.*name|lname|surname|last$|secondname|family.*name",
          "negative": "surname\\d",
          "score": 0.9,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT"
          ]
        }
      ]
    },
    {
      "type": "FULL_NAME",
      "kind": "full_name",
      "variants": [
        {
          "positive": "^name|full.?name|your.?name|customer.?name|bill.?name|ship.?name|name.*first.*last|firstandlastname|contact.?(name|person)|receiver",
          "negative": null,
          "score": 0.9,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT"
          ]
        }
      ]
    },
    {
      "type": "EMAIL_ADDRESS",
      "kind": "email",
      "variants": [
        {
          "positive": "e.?mail",
          "negative": null,
          "score": 1.4,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT",
            "INPUT_EMAIL"
          ]
        }
      ]
    },
    {
      "type": "PHONE",
      "kind": "phone",
      "variants": [
        {
          "positive": "phone|mobile|contact.?number",
          "negative": null,
          "score": 1.2,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT",
            "INPUT_TELEPHONE",
            "INPUT_NUMBER"
          ]
        }
      ]
    },
    {
      "type": "ADDRESS_LINE_1",
      "kind": "address_line1",
      "variants": [
        {
          "positive": "^address$|address[_-]?line(one)?|address1|addr1|street|(?:shipping|billing)address$|house.?name",
          "negative": null,
          "score": 1.1,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT",
            "INPUT_SEARCH"
          ]
        },
        {
          "positive": "(^\\W*address)|(address\\W*$)|(?:shipping|billing|mailing|pick.?up|drop.?off|delivery|sender|postal|recipient|home|work|office|school|business|mail)[\\s\\-]+address|address\\s+(of|for|to|from)|street.*(house|building|apartment|floor)|(house|building|apartment|floor).*street",
          "negative": null,
          "score": 1.1,
          "attributes": [
            "LABEL"
          ],
          "controls": [
            "INPUT_TEXT",
            "INPUT_SEARCH"
          ]
        }
      ]
    },
    {
      "type": "ADDRESS_LINE_2",
      "kind": "address_line2",
      "variants": [
        {
          "positive": "address[_-]?line(2|two)|address2|addr2|street|suite|unit",
          "negative": null,
          "score": 1.1,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT"
          ]
        },
        {
          "positive": "address|line",
          "negative": null,
          "score": 1.1,
          "attributes": [
            "LABEL"
          ],
          "controls": [
            "INPUT_TEXT"
          ]
        }
      ]
    },
    {
      "type": "CITY",
      "kind": "city",
      "variants": [
        {
          "positive": "(?<!(?:pa|ri|li|di|ni|lo))city|town|suburb",
          "negative": null,
          "score": 1.1,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT",
            "SELECT_ONE",
            "INPUT_SEARCH"
          ]
        }
      ]
    },
    {
      "type": "STATE",
      "kind": "region",
      "variants": [
        {
          "positive": "(?<!(united|hist|history).?)state|region|province|county|principality",
          "negative": null,
          "score": 1.1,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT",
            "SELECT_ONE",
            "INPUT_SEARCH"
          ]
        }
      ]
    },
    {
      "type": "ZIP_CODE",
      "kind": "postal_code",
      "variants": [
        {
          "positive": "(?<!\\.)zip|postal|post.*code|pcode|pin.?code",
          "negative": null,
          "score": 1.1,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT",
            "INPUT_TELEPHONE",
            "INPUT_NUMBER"
          ]
        }
      ]
    },
    {
      "type": "COUNTRY",
      "kind": "country",
      "variants": [
        {
          "positive": "country|countries",
          "negative": null,
          "score": 1.1,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT",
            "SELECT_ONE",
            "INPUT_SEARCH"
          ]
        }
      ]
    },
    {
      "type": "COMPANY_NAME",
      "kind": "current_employer",
      "variants": [
        {
          "positive": "company|business|organization|organisation",
          "negative": null,
          "score": 1.1,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT"
          ]
        }
      ]
    }
  ],
  "vetoes": [
    {
      "type": "SEARCH_TERM",
      "scope": null,
      "variants": [
        {
          "positive": "^q$|search|query|qry",
          "negative": null,
          "score": 0.8,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT",
            "TEXT_AREA",
            "INPUT_SEARCH"
          ]
        }
      ]
    },
    {
      "type": "CREDIT_CARD_NUMBER",
      "scope": null,
      "variants": [
        {
          "positive": "(?:card|cc|acct).?(?:number|#|no|num|field(?!s)|pan)|0000 ?0000 ?0000 ?0000|1234 ?1234 ?1234 ?1234|^xxxx ?xxxx ?xxxx ?xxxx$",
          "negative": null,
          "score": 1,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT",
            "INPUT_TELEPHONE",
            "INPUT_PASSWORD",
            "INPUT_NUMBER"
          ]
        }
      ]
    },
    {
      "type": "CREDIT_CARD_VERIFICATION_CODE",
      "scope": null,
      "variants": [
        {
          "positive": "verification|card.?identification|security.?code|card.?code|security.?value|security.?number|card.?pin|c-v-v|(?:cvn|cvv|cvc|csc|cvd|ccv)|\\bcid\\b|cccid",
          "negative": null,
          "score": 1,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT",
            "INPUT_TELEPHONE",
            "INPUT_PASSWORD",
            "INPUT_NUMBER"
          ]
        }
      ]
    },
    {
      "type": "ONE_TIME_CODE",
      "scope": null,
      "variants": [
        {
          "positive": "otp|verification.code|2fa|six.digit",
          "negative": null,
          "score": 1.1,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT",
            "INPUT_NUMBER"
          ]
        }
      ]
    },
    {
      "type": "IBAN_VALUE",
      "scope": null,
      "variants": [
        {
          "positive": "(\\biban(\\b|_)|international bank account number)",
          "negative": null,
          "score": 0.975,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT",
            "TEXT_AREA",
            "INPUT_NUMBER"
          ]
        }
      ]
    },
    {
      "type": "MERCHANT_PROMO_CODE",
      "scope": null,
      "variants": [
        {
          "positive": "(promo(tion|tional)?|gift|discount|coupon)[-_. ]*code",
          "negative": null,
          "score": 0.85,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT"
          ]
        }
      ]
    },
    {
      "type": "NAME_IGNORED",
      "scope": [
        "given_name",
        "family_name",
        "full_name",
        "preferred_name"
      ],
      "variants": [
        {
          "positive": "user.?name|user.?id|nickname|maiden name|title|prefix|suffix|mail",
          "negative": null,
          "score": 0.9,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT",
            "SELECT_ONE",
            "INPUT_SEARCH"
          ]
        }
      ]
    },
    {
      "type": "ADDRESS_NAME_IGNORED",
      "scope": [
        "address_line1",
        "address_line2",
        "city",
        "region",
        "postal_code",
        "country"
      ],
      "variants": [
        {
          "positive": "(?:address|location).*(?:nickname|label|type)",
          "negative": "e.?mail|re.?type|typed",
          "score": 1.1,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT",
            "SELECT_ONE",
            "INPUT_SEARCH"
          ]
        }
      ]
    },
    {
      "type": "ATTENTION_IGNORED",
      "scope": [
        "address_line1",
        "address_line2"
      ],
      "variants": [
        {
          "positive": "attention|attn",
          "negative": null,
          "score": 1.1,
          "attributes": [
            "LABEL",
            "NAME"
          ],
          "controls": [
            "INPUT_TEXT"
          ]
        }
      ]
    }
  ]
} as const;
